export const LANGUAGES = {
  en: { code: "en_US", name: "english" },
  ru: { code: "ru_RU", name: "русский" },
  // cs: { code: "cs_CZ", name: "čeština" },
  // de: { code: "de_DE", name: "deutsch" },
  // el: { code: "el_GR", name: "ελληνικά" },
  // es: { code: "es_ES", name: "español" },
  // fr: { code: "fr_FR", name: "français" },
  // hu: { code: "hu_HU", name: "magyar" },
  // id: { code: "id_ID", name: "indonesian" },
  // it: { code: "it_IT", name: "italiano" },
  // ja: { code: "ja_JP", name: "日本語" },
  // ko: { code: "ko_KR", name: "한국어" },
  // pl: { code: "pl_PL", name: "polski" },
  // pt: { code: "pt_BR", name: "português" },
  // ro: { code: "ro_RO", name: "română" },
  // th: { code: "th_TH", name: "ภาษาไทย" },
  // tr: { code: "tr_TR", name: "türkçe" },
  // vi: { code: "vi_VN", name: "tiếng việt" },
  // zh: { code: "zh_CN", name: "中國人" },
} as const;
