import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "@/styles/index.css";
import { FC, PropsWithChildren } from "react";
import Background from '@/components/Background';

const font = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "League of Skins",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html className={`${font.variable} h-full antialiased light`}>
      <body className='min-h-full flex flex-col' >
        <Background />
        <div className='z-1'>{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
