import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "@/styles/index.css";
import { FC, PropsWithChildren } from "react";
import Background from "@/components/Background";
import { getDictionary, getLocale } from "@/lib/i18n";
import { DictionaryProvider } from "@/shared/providers/DictionaryProvider";
import { UserProvider } from "@/shared/providers/UserProvider";
import ToastsProvider from "@/shared/providers/ToastsProvider";
import localFont from "next/font/local";

const font = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const mono = localFont({
  src: [
    {
      path: "../public/fonts/JetBrainsMono.ttf",
      style: "normal",
    },
  ],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "League of Skins",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => {
  const locale = await getLocale();
  const dictionary = await getDictionary();

  return (
    <html className={`${font.variable} ${mono.variable} h-full antialiased light`}>
      <body className="min-h-full flex flex-col">
        <Background />
        <DictionaryProvider dictionary={dictionary} locale={locale}>
          <UserProvider>
            <ToastsProvider />
            <div className="z-1">{children}</div>
          </UserProvider>
        </DictionaryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
