import type { Metadata } from "next";
import { Rubik, Geist } from "next/font/google";
import "@/styles/index.css";
import localFont from "next/font/local";
import { I18nProvider } from "next-i18next/client";
import { initServerI18next, getT, getResources, generateI18nStaticParams } from "next-i18next/server";

import Background from "@/components/Background";
import { TooltipProvider } from "@/components/ui/tooltip";
import { getServerUserPayload } from "@/lib/auth";
import { getLangCookie } from "@/lib/cookies";
import { cn } from "@/shared/cn";
import { AppProvider } from "@/shared/providers/AppProvider";
import { AuthProvider } from "@/shared/providers/AuthProvider";
import QueryProvider from "@/shared/providers/QueryProvider";
import ToastsProvider from "@/shared/providers/ToastsProvider";

import i18nConfig from "../i18n.config";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

initServerI18next(i18nConfig);

export async function generateStaticParams() {
  return generateI18nStaticParams();
}

const font = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const mono = localFont({
  src: [
    {
      path: "../public/fonts/JetBrainsMono.ttf",
      style: "normal",
    },
  ],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "League of Skins",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const lng = await getLangCookie();
  const userPayload = await getServerUserPayload();
  const { userId } = userPayload ?? {};

  const { i18n } = await getT();
  const resources = getResources(i18n);

  return (
    <html
      className={cn("h-full", "antialiased", "dark", font.variable, mono.variable, "font-sans", geist.variable)}
      lang={lng}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Background />

        <I18nProvider language={lng} resources={resources}>
          <QueryProvider>
            <AuthProvider initialUserId={userId}>
              <ToastsProvider />
              <AppProvider>
                <TooltipProvider>
                  <div className="z-1">{children}</div>
                </TooltipProvider>
              </AppProvider>
            </AuthProvider>
          </QueryProvider>
        </I18nProvider>
      </body>
    </html>
  );
};

export default RootLayout;
